Controllers/LOC_CountryController.cs
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.Common;
using System.Data.SqlClient;
using System.Reflection;

namespace AddressBook.Controllers
{
    public class LOC_CountryController : Controller
    {
        public IConfiguration Configuration { get; set; }

        public LOC_CountryController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        #region SelectAll
        public IActionResult Index(/*string? CountryName*/)
        {
            //if (CountryName == null)
            //{
                //CountryName = "";
                SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
                conn.Open();
                SqlCommand cmd = conn.CreateCommand();
                cmd.CommandType = System.Data.CommandType.StoredProcedure;
                cmd.CommandText = "PR_Country_SelectAll";
                SqlDataReader reader = cmd.ExecuteReader();
                DataTable dt = new DataTable();
                dt.Load(reader);
                conn.Close();
                return View("LOC_CountryList", dt);
            //}
            //else
            //{
            //    SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            //    conn.Open();
            //    SqlCommand cmd = conn.CreateCommand();
            //    cmd.CommandType = CommandType.StoredProcedure;
            //    cmd.CommandText = "PR_Search_Country";
            //    cmd.Parameters.AddWithValue("@name", CountryName);
            //    SqlDataReader reader = cmd.ExecuteReader();
            //    DataTable dt = new DataTable();
            //    dt.Load(reader);
            //    conn.Close();
            //    return View("LOC_CountryList", dt);
            //}

        }
        #endregion

        #region AddCountry
        public IActionResult AddEditCountry(LOC_CountryModel modelLOC_Country, int CountryID = 0)
        {
            if (string.IsNullOrEmpty(modelLOC_Country.CountryName))
            {
                ModelState.AddModelError("CountryName", "CountryName is required");
            }
            if (string.IsNullOrEmpty(modelLOC_Country.CountryCode))
            {
                ModelState.AddModelError("CountryCode", "CountryCode is required");
            }
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            if (ModelState.IsValid)
            {
                if (CountryID == 0)
                {
                    cmd.CommandText = "PR_Country_Insert";
                }
                else
                {
                    cmd.CommandText = "PR_Country_UpdateByPK";
                    cmd.Parameters.AddWithValue("@CountryID", modelLOC_Country.CountryId);
                }
                cmd.Parameters.AddWithValue("@CountryName", modelLOC_Country.CountryName);
                cmd.Parameters.AddWithValue("@CountryCode", modelLOC_Country.CountryCode);
                cmd.ExecuteNonQuery();
                return RedirectToAction("Index");
            }
            conn.Close();
            return View("LOC_CountryAddEdit", modelLOC_Country);
        }
        public IActionResult LOC_CountryAddEdit()
        {
            return View();
        }
        #endregion

        #region EditCountry
        public IActionResult SelectByPK(int? CountryID)
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            LOC_CountryModel model = new LOC_CountryModel();
            if (CountryID == null)
            {
                CountryID = -1;
            }
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Country_SelectByPK";
            cmd.Parameters.AddWithValue("@CountryID", CountryID);
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            foreach (DataRow data in dt.Rows)
            {
                model.CountryName = data["CountryName"].ToString();
                model.CountryCode = data["CountryCode"].ToString();
                model.CountryId = int.Parse(data["CountryID"].ToString());
            }
            conn.Close();
            return View("LOC_CountryAddEdit", model);
        }
        #endregion

        #region DeleteCountry
        public IActionResult DeleteByPK(int CountryID)
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_Country_DeleteByPK";
            cmd.Parameters.AddWithValue("@CountryID", CountryID);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }
        #endregion
    }
}

Controllers/LOC_StateController.cs
using AddressBook.Models;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using System.Data.SqlClient;

namespace AddressBook.Controllers
{
    public class LOC_StateController : Controller
    {

        public IConfiguration Configuration { get; set; }

        public LOC_StateController(IConfiguration configuration)
        {
            Configuration = configuration;
        }

        public IActionResult Index()
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = System.Data.CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_SelectAll";
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            if (reader.HasRows)
            {
                dt.Load(reader);
            }
            return View(dt);
        }

        public IActionResult SelectByPK(int? StateId) 
        {
            FillCountryDDL();
            if(StateId == null)
            {
                StateId = -1;
            }
            SqlConnection conn = new SqlConnection(Configuration.GetConnectionString("Default"));
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_SelectByPK";
            cmd.Parameters.AddWithValue("@StateID",StateId);
            SqlDataReader reader = cmd.ExecuteReader();
            DataTable dt = new DataTable();
            dt.Load(reader);
            LOC_StateModel stateModel = new LOC_StateModel();
            foreach (DataRow data in dt.Rows)
            {
                stateModel.StateName = data["StateName"].ToString();
                stateModel.CountryID = Convert.ToInt32(data["CountryID"]);
                stateModel.StateCode = data["StateCode"].ToString();
            }
            conn.Close();
            return View("LOC_StateAddEdit", stateModel);
        }

        [HttpPost]
        public IActionResult Add(LOC_StateModel modelLOC_State, int StateID = 0)
        {
            SqlConnection conn = new SqlConnection(Configuration.GetConnectionString("Default"));
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            if(StateID == 0)
            {
                cmd.CommandText = "PR_State_Insert";
            }
            else
            {
                cmd.CommandText = "PR_State_UpdateByPK";
                cmd.Parameters.AddWithValue("@StateId", modelLOC_State.StateId);
            }

            cmd.Parameters.AddWithValue("@StateName", modelLOC_State.StateName);
            cmd.Parameters.AddWithValue("@CountryID", modelLOC_State.CountryID);
            cmd.Parameters.AddWithValue("@StateCode", modelLOC_State.StateCode);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }

        public IActionResult AddEditState()
        {
            FillCountryDDL();
            return View("LOC_StateAddEdit");
        }

        public IActionResult DeleteByPK(int StateID)
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            conn.Open();
            SqlCommand cmd = conn.CreateCommand();
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_State_DeleteByPK";
            cmd.Parameters.AddWithValue("@StateID",StateID);
            cmd.ExecuteNonQuery();
            conn.Close();
            return RedirectToAction("Index");
        }

        public void FillCountryDDL()
        {
            SqlConnection conn = new SqlConnection(this.Configuration.GetConnectionString("Default"));
            List<LOC_CountryDropDownModel> country = new List<LOC_CountryDropDownModel>();
            conn.Open();
            SqlCommand cmd = new SqlCommand();
            cmd.Connection = conn;
            cmd.CommandType = CommandType.StoredProcedure;
            cmd.CommandText = "PR_DropDown_CountryName";
            SqlDataReader reader = cmd.ExecuteReader();
            while (reader.Read())
            {
                LOC_CountryDropDownModel countryModel = new LOC_CountryDropDownModel()
                {
                    CountryID = Convert.ToInt32(reader["CountryID"]),
                    CountryName = reader["CountryName"].ToString()
                };
                country.Add(countryModel);
            }
            reader.Close();
            conn.Close();
            ViewBag.CountryList = country;
        }


    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AddressBook</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AddressBook.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">AddressBook</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LOC_Country" asp-action="Index">Country List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="LOC_State" asp-action="Index">State List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="LOC_City" asp-controller="LOC_City" asp-action="Index">City List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="LOC_Cascade" asp-controller="LOC_Cascade" asp-action="Index">Cascade dropdown</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="LOC_Branch" asp-controller="LOC_Branch" asp-action="Index">Branch List</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - AddressBook - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>